version: '2'

services:
  drinkman:
    build: .
    command: uwsgi --ini uwsgi.ini #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: SECRET
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: drinkman
      DB_USER: postgres
      DB_PW: password
    restart: always
