version: '3.3'

services:
  db_dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkman
#    volumes:
#      - ../drinkman-postgres-data/:/var/lib/postgresql/data
  drinkman:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    restart: always
    volumes:
      - .:/code
    environment:
      DJANGO_SECRET: SECRET
      DB_HOST: db_dev
      DB_PORT: 5432
      DB_NAME: drinkman
      DB_USER: postgres
      DB_PW: password
      DJANGO_DEV: 'false'
      HOSTNAME: ALLOWED_HOST.localhost
    depends_on:
      - db_dev
    networks:
      - default 
    labels:
      - "traefik.http.routers.drinkman.rule=Host(`HOST`)"

networks:
  default:
    external:
      name: 'web'
