# Generated by Django 3.1.2 on 2020-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0009_auto_20201017_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
